spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # 默認使用local配置

---
# 本地開發環境配置
spring:
  config:
    activate:
      on-profile: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/neutec-blog?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: Aaa123123
    # HikariCP配置
    hikari:
      pool-name: HikariPool-Member
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000        # 5分鐘
      connection-timeout: 20000   # 20秒
      max-lifetime: 1200000      # 20分鐘
      auto-commit: true
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        # 性能優化設置
        jdbc.batch_size: 50
        jdbc.fetch_size: 50
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: false
        query.fail_on_pagination_over_collection_fetch: true
        query.in_clause_parameter_padding: true
        query.plan_cache_max_size: 2048
        generate_statistics: false # 生產環境建議關閉
        cache:
          use_second_level_cache: false
          use_query_cache: false
    open-in-view: false # 避免延遲加載問題
---
# local-prod開發配置
spring:
  config:
    activate:
      on-profile: l-prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.80.133.178:3306/neutec-blog?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: +7Q+=1JBMm5][N}h
    # HikariCP配置
    hikari:
      pool-name: HikariPool-Member
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000        # 5分鐘
      connection-timeout: 20000   # 20秒
      max-lifetime: 1200000      # 20分鐘
      auto-commit: true
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        # 性能優化設置
        jdbc.batch_size: 50
        jdbc.fetch_size: 50
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: false
        query.fail_on_pagination_over_collection_fetch: true
        query.in_clause_parameter_padding: true
        query.plan_cache_max_size: 2048
        generate_statistics: false # 生產環境建議關閉
        cache:
          use_second_level_cache: false
          use_query_cache: false
    open-in-view: false # 避免延遲加載問題

---
# prod開發配置
spring:
  config:
    activate:
      on-profile: production
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///neutec-blog?cloudSqlInstance=${CLOUD_SQL_INSTANCE}&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}
    # HikariCP配置
    hikari:
      pool-name: HikariPool-Member
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000        # 5分鐘
      connection-timeout: 20000   # 20秒
      max-lifetime: 1200000      # 20分鐘
      auto-commit: true
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        # 性能優化設置
        jdbc.batch_size: 50
        jdbc.fetch_size: 50
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: false
        query.fail_on_pagination_over_collection_fetch: true
        query.in_clause_parameter_padding: true
        query.plan_cache_max_size: 2048
        generate_statistics: false # 生產環境建議關閉
        cache:
          use_second_level_cache: false
          use_query_cache: false
    open-in-view: false # 避免延遲加載問題
---

logging:
  level:
    org.hibernate.SQL: INFO  # 開發環境可以開啟，生產環境建議關閉
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: INFO


jwt:
  secret: test
  expiration: 86400000

spring:
  port: 8080
  liquibase:
    change-log: classpath:/changelog.xml